### ISSUE TITLE
Config to link player names instead of having 2 icons

### ISSUE THREAD

**Issue by Bara** [surftimer/SurfTimer-Web-Stats#13]
![image](https://user-images.githubusercontent.com/17928280/167314632-adb9d04f-c055-4531-9315-6d90fd96cc11.png)
I think it would look bit cleaner with just the steam icon behind player names and link the player name to the players stats page.

**Comment by KristianP26** [comment]
Maybe steam profile can be accessible only from user profile

**Comment by KristianP26** [comment]
Or buttons
![image](https://user-images.githubusercontent.com/28766334/167738464-fdc0113b-5abf-4912-8aa0-ac711736f226.png)

**Comment by KristianP26** [comment]
It can look good with flag.

**Comment by KristianP26** [comment]
@Bara

**Comment by KristianP26** [comment]
https://github.com/surftimer/SurfTimer-Web-Stats/commit/1f5211c85cc194dd08fcf0d5c8e68a1adc4fd7e0
