### ISSUE TITLE
Bug Player Profiles

### ISSUE THREAD

**Issue by Senziousjs** [surftimer/SurfTimer-Web-Stats#76]
Player Profiles doesnt load

**Comment by KristianP26** [comment]
Provide some more info:
Which version are you using?
Standalone or Docker?
Do you have the required PHP version?
Provide your web server log.

**Comment by Senziousjs** [comment]
Hello,

 

here my informations:

 


Provide some more info:
Which version are you using?

Latest Version > Surftimer-Web-Stats v.2.13


Standalone or Docker?

Standalone


Do you have the required PHP version?

PHP Version 7.4.33


Provide your web server log.


Sorry, i dont know where can i find it..

 

Thanks :)

 

 


Gesendet: Freitag, 17. Februar 2023 um 10:29 Uhr
Von: "Kristián Partl" ***@***.***>
An: "surftimer/SurfTimer-Web-Stats" ***@***.***>
Cc: "Senziousjs" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [surftimer/SurfTimer-Web-Stats] Bug Player Profiles (Issue #76)


 

Provide some more info:
Which version are you using?
Standalone or Docker?
Do you have the required PHP version?
Provide your web server log.

**Comment by KristianP26** [comment]
You're using old PHP version it is required to use PHP 8.0 or above.

**Comment by Senziousjs** [comment]
Thanks for your replay. I Update my Version from 7 to 8 soon. Thank you!
